<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    $params = [
        'versie' => '2.10',
        'actie' => 'delete',
        'voertuignr_hexon' => '12491891',
        'voertuignr' => '137741',
        'voertuigsoort' => 'MACHINE',
        'klantnummer' => '25201',
        'merk' => 'Accord',
        'model' => '',
        'type' => 'DL pneumaitsch',
        'carrosserie' => 'Zaaimachine',
        'brandstof' => 'O',
        'transmissie' => '',
        'btw_marge' => 'B',
        'nieuw' => 'n',
        'verwacht' => 'n',
        'gereserveerd' => 'n',
        'basiskleur' => 'overig',
        'kleur' => '',
        'verkoopprijs_particulier_bpm' => '',
        'verkoopprijs_particulier_btw' => '',
        'actieprijs_bpm' => '',
        'actieprijs_btw' => '',
        'verkoopprijs_handel_bpm' => '',
        'verkoopprijs_handel_btw' => '',
        'opmerkingen' => 'Accord pneumatische zaaimachine DL<br />- met na loop eg<br />- met na loop rol<br /><br /><br />Lely 300-25 kopeg<br />- met hef inrichting<br />- met packerwals',
        'opmerkingen_engels' => '',
        'opmerkingen_duits' => '',
        'opmerkingen_frans' => '',
        'opmerkingen_spaans' => '',
        'opmerkingen_portugees' => '',
        'opmerkingen_italiaans' => '',
        'opmerkingen_grieks' => '',
        'opmerkingen_russisch' => '',
        'opmerkingen_roemeens' => '',
        'opmerkingen_hongaars' => '',
        'opmerkingen_pools' => '',
        'opmerkingen_tsjechisch' => '',
        'opmerkingen_bulgaars' => '',
        'opmerkingen_kroatisch' => '',
        'opmerkingen_handel' => '',
        'opmerkingen_handel_engels' => '',
        'opmerkingen_handel_duits' => '',
        'opmerkingen_handel_frans' => '',
        'opmerkingen_handel_spaans' => '',
        'opmerkingen_handel_portugees' => '',
        'opmerkingen_handel_italiaans' => '',
        'opmerkingen_handel_grieks' => '',
        'opmerkingen_handel_russisch' => '',
        'opmerkingen_handel_roemeens' => '',
        'opmerkingen_handel_hongaars' => '',
        'opmerkingen_handel_pools' => '',
        'opmerkingen_handel_tsjechisch' => '',
        'opmerkingen_handel_bulgaars' => '',
        'opmerkingen_handel_kroatisch' => '',
        'titel' => '',
        'titel_engels' => '',
        'titel_duits' => '',
        'titel_frans' => '',
        'titel_spaans' => '',
        'titel_portugees' => '',
        'titel_italiaans' => '',
        'titel_grieks' => '',
        'titel_russisch' => '',
        'titel_roemeens' => '',
        'titel_hongaars' => '',
        'titel_pools' => '',
        'titel_tsjechisch' => '',
        'titel_bulgaars' => '',
        'titel_kroatisch' => '',
        'highlights' => '',
        'highlights_engels' => '',
        'highlights_duits' => '',
        'highlights_frans' => '',
        'highlights_spaans' => '',
        'highlights_portugees' => '',
        'highlights_italiaans' => '',
        'highlights_grieks' => '',
        'highlights_russisch' => '',
        'highlights_roemeens' => '',
        'highlights_hongaars' => '',
        'highlights_pools' => '',
        'highlights_tsjechisch' => '',
        'highlights_bulgaars' => '',
        'highlights_kroatisch' => '',
        'zoektermen' => '',
        'zoektermen_engels' => '',
        'zoektermen_duits' => '',
        'zoektermen_frans' => '',
        'zoektermen_spaans' => '',
        'zoektermen_portugees' => '',
        'zoektermen_italiaans' => '',
        'zoektermen_grieks' => '',
        'zoektermen_russisch' => '',
        'zoektermen_roemeens' => '',
        'zoektermen_hongaars' => '',
        'zoektermen_pools' => '',
        'zoektermen_tsjechisch' => '',
        'zoektermen_bulgaars' => '',
        'zoektermen_kroatisch' => '',
        'standaardopmerkingen' => 'Buts Meulepas, al jaren DE specialist in machines voor landbouw, tuin en park. Al meer dan dertig jaar zijn wij leverancier van tal van gerenommeerde merken landbouwmachines en machines voor de aanleg en het onderhoud van tuin en park. Daarnaast is Buts Meulepas, onder de huismerken BM en Goudland, gespecialiseerd in het zelf produceren van machines.',
        'standaardopmerkingen_engels' => '',
        'standaardopmerkingen_duits' => '',
        'standaardopmerkingen_frans' => '',
        'standaardopmerkingen_spaans' => '',
        'standaardopmerkingen_portugees' => '',
        'standaardopmerkingen_italiaans' => '',
        'standaardopmerkingen_grieks' => '',
        'standaardopmerkingen_russisch' => '',
        'standaardopmerkingen_roemeens' => '',
        'standaardopmerkingen_hongaars' => '',
        'standaardopmerkingen_pools' => '',
        'standaardopmerkingen_tsjechisch' => '',
        'standaardopmerkingen_bulgaars' => '',
        'standaardopmerkingen_kroatisch' => '',
        'apk_bij_aflevering' => 'n',
        'vermogen_motor_pk' => '0',
        'bpm_bedrag' => '0',
        'nap_weblabel' => 'n',
        'onderhoudsboekjes' => '',
        'exportprijs_btw' => '',
        'meeneemprijs_bpm' => '',
        'meeneemprijs_btw' => '',
        'kosten_rijklaar' => '0',
        'schadevoertuig' => 'n',
        'consignatie' => 'n',
        'demovoertuig' => 'n',
        'merkgarantie' => '',
        'autotrust_garantie' => 'n',
        'vakgarant_premium_occasion' => 'n',
        'vwe_occasion_garant_plan' => 'n',
        'opmerkingen_garantie' => '',
        'wegenbelasting_kwartaal_min' => '',
        'wegenbelasting_kwartaal_max' => '',
        'verkocht' => 'n',
        'bijtelling_pct' => '0',
        'verkocht_datum' => '',
        'verlengd' => '',
        'verhoogd' => '',
        'verhuur' => 'n',
        'klassieker' => 'n',
        'land' => 'nl',
        'munteenheid' => 'EUR',
        'volautomatisch' => '',
        'voortbeweging_zelfstandig' => '',
        'verplaatsing' => '',
        'generatorvermogen' => '',
        'generatorvermogen_eenheid' => '',
        'doorvoercapaciteit' => '',
        'doorvoercapaciteit_eenheid' => '',
        'maximale_reikwijdte' => '',
        'maximale_reikwijdte_eenheid' => '',
        'voedingsspanning' => '',
        'voedingsspanning_eenheid' => '',
        'mastlengte' => '',
        'mastlengte_eenheid' => '',
        'bovenarmlengte' => '',
        'bovenarmlengte_eenheid' => '',
        'rupsbandbreedte' => '',
        'rupsbandbreedte_eenheid' => '',
        'laadschopinhoud' => '',
        'laadschopinhoud_eenheid' => '',
        'minimale_koeltemperatuur' => '',
        'minimale_koeltemperatuur_eenheid' => '',
        'maximale_koeltemperatuur' => '',
        'maximale_koeltemperatuur_eenheid' => '',
        'toepassingsmateriaal' => '',
        'toepassingsgebied' => 'landbouw',
        'ce_markering' => 'n',
        'rompmateriaal' => '',
        'attachment_passend_op' => '',
        'hefwerktuigaansluiting' => '',
        'snelwisselsysteem' => '',
        'pantograaf' => '',
        'wals_trillend' => '',
        'prijstype' => 'op aanvraag',
        'bieden_toestaan' => '',
        'oldtimer' => '',
        'accessoires' => '',
        'afbeeldingen' => 'http://images1.doorlinkenvoorraad.nl/s1474544109/12491891-1-2-3.jpg?do_not_embed,http://images1.doorlinkenvoorraad.nl/s1474544109/12491891-2-2-3.jpg?do_not_embed,http://images1.doorlinkenvoorraad.nl/s1474544109/12491891-3-2-3.jpg?do_not_embed,http://images1.doorlinkenvoorraad.nl/s1474544109/12491891-4-2-3.jpg?do_not_embed,http://images1.doorlinkenvoorraad.nl/s1474544109/12491891-5-2-3.jpg?do_not_embed,http://images1.doorlinkenvoorraad.nl/s1474544050/12491891-6-2-3.jpg?do_not_embed,http://images1.doorlinkenvoorraad.nl/s1474544110/12491891-7-2-3.jpg?do_not_embed,http://images1.doorlinkenvoorraad.nl/s1474544110/12491891-8-2-3.jpg?do_not_embed,'
    ];

    return view('welcome', compact('params'));
});

Route::post('/inventory', 'InventoryController@store');

Route::post('/test', function () {
    \Illuminate\Support\Facades\Storage::disk('local')->put('file.txt', print_r(request()->all(), true));
});